/**
 * Pair contracts over the gateway's wire fixtures.
 *
 * The fixtures under test/fixtures/gateway-wire/ at the repository root are
 * generated by the gateway's real builders and vendored verbatim; the
 * coordination repository's pair-fixtures gate keeps the copies in sync. Each
 * test runs this CLI's own parser or validator over one fixture, so a gateway
 * shape change fails here, offline, instead of inside a purchase. 0.1.0 had no
 * such test and could not read one live gateway result.
 */
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import type { Address } from "viem";
import {
  bindingFromExtensions,
  validateOrderActionChallenge,
  validateWalletActionChallenge,
} from "@daski/x402-scheme";
import { GatewayClient, type McpToolResult } from "../src/gateway/client.js";

type Json = Record<string, unknown>;

const AUDIENCE = "https://sandbox-gateway.daski.io";
const CHAIN_ID = 84_532;
/** The fixtures were issued at this second; their 300 s windows are checked against it. */
const FIXTURE_NOW = 1_756_769_000;
const HANDLE = "A".repeat(43);
const INTENT_ID = "int_00000000-0000-4000-8000-000000000002";
const PAYER = `0x${"a".repeat(40)}` as Address;

function fixtureDirectory(): string {
  let directory = dirname(fileURLToPath(import.meta.url));
  for (let depth = 0; depth < 8; depth += 1) {
    const candidate = join(directory, "test", "fixtures", "gateway-wire");
    if (existsSync(join(candidate, "mcp-result.json"))) return candidate;
    directory = dirname(directory);
  }
  throw new Error(
    "gateway wire fixtures are missing: re-vendor test/fixtures/gateway-wire/ from the gateway",
  );
}

function fixture<T = Json>(name: string): T {
  return JSON.parse(readFileSync(join(fixtureDirectory(), name), "utf8")) as T;
}

const mcpResult = fixture<{
  success: McpToolResult;
  error: McpToolResult;
  paymentRequired: McpToolResult;
}>("mcp-result.json");
const prepared = fixture<McpToolResult & { structuredContent: Json }>("payment-challenge-prepared.json");
const walletChallenge = fixture("wallet-challenge.json");
const orderActionChallenge = fixture("order-action-challenge.json");
const railErrors = fixture<{
  walletAuthorizationInvalid: { error: Json };
  authorizationWindow: { error: Json };
  requestSchemaInvalid: { error: Json };
  mcpWalletAccessDenied: McpToolResult;
}>("standard-rail-error.json");

test("mcp-result: an ordinary result is read from structuredContent, and its text block carries the same JSON", () => {
  const body = GatewayClient.json(mcpResult.success);
  assert.deepEqual(body, mcpResult.success.structuredContent);
  assert.deepEqual(body, { orderHandle: HANDLE, state: "FULFILLED" });
  assert.equal(GatewayClient.unreadable(mcpResult.success), false);
  const text = mcpResult.success.content[0]?.text;
  assert.ok(typeof text === "string");
  assert.deepEqual(JSON.parse(text), mcpResult.success.structuredContent);
});

test("mcp-result: an error carries its code where purchaseFailure looks for it", () => {
  assert.equal(mcpResult.error.isError, true);
  assert.equal(GatewayClient.json(mcpResult.error)?.code, "WALLET_ACCESS_DENIED");
  assert.equal(GatewayClient.unreadable(mcpResult.error), false);
});

test("mcp-result: the unpaid buy call's challenge is read from _meta and matches the body", () => {
  const reply = mcpResult.paymentRequired;
  assert.equal(reply.isError, true);
  const challenge = GatewayClient.challenge(reply);
  assert.deepEqual(challenge, reply._meta?.["x402/payment-required"]);
  assert.deepEqual(challenge, reply.structuredContent);
  assert.equal(challenge?.x402Version, 2);
});

test("payment-challenge-prepared: the challenge is read from _meta, the nested body agrees, and the preflight is present", () => {
  assert.equal(prepared.isError, undefined);
  const challenge = GatewayClient.challenge(prepared);
  assert.ok(challenge, "the prepare tool's challenge must be readable");
  assert.deepEqual(challenge, prepared._meta?.["x402/payment-required"]);
  assert.deepEqual(challenge, prepared.structuredContent.paymentRequired);
  // And without _meta, the nested body alone must still yield it.
  assert.deepEqual(GatewayClient.challenge({ ...prepared, _meta: undefined }), challenge);

  const requirement = challenge.accepts[0];
  assert.ok(requirement);
  assert.equal(requirement.scheme, "exact");
  assert.equal(requirement.network, "eip155:84532");
  assert.match(requirement.amount, /^\d+$/);
  assert.match(requirement.payTo, /^0x[0-9a-fA-F]{40}$/);
  assert.equal(typeof requirement.maxTimeoutSeconds, "number");
  assert.equal(typeof requirement.extra?.name, "string");
  assert.equal(typeof requirement.extra?.version, "string");
  assert.equal(requirement.extra?.assetTransferMethod, "eip3009");

  const preflight = GatewayClient.preflight(prepared);
  assert.ok(preflight);
  assert.equal(preflight.sufficient, true);
  assert.equal(preflight.intentId, INTENT_ID);
  assert.equal(typeof preflight.approvalSummary, "string");
  assert.equal(GatewayClient.json(prepared)?.orderHandle, HANDLE);

  // The recipe binding the policy validator recomputes from is readable too.
  const bindings = (challenge.extensions as Json)["daski-order-binding"] as Record<string, Json>;
  const binding = bindingFromExtensions({ "daski-order-binding": bindings["recipe-bound-v2"] });
  assert.ok(binding, "the v2 order binding must parse");
  assert.equal(typeof binding.expiresAt, "number");
});

test("wallet-challenge: the envelope is what callWalletQuery expects and the challenge validates", () => {
  assert.equal(walletChallenge.authorizationRequired, true);
  assert.equal(walletChallenge.code, "WALLET_AUTHORIZATION_REQUIRED");
  const validated = validateWalletActionChallenge(walletChallenge.challenge, CHAIN_ID, {
    payer: PAYER,
    action: "list-orders",
    audience: AUDIENCE,
    request: { limit: 25, cursor: null },
    requireProviderBinding: false,
    nowSeconds: FIXTURE_NOW,
  });
  assert.equal(validated.domain.name, "DaskiStandardWallet");
  assert.equal(String(validated.message.payer).toLowerCase(), PAYER);
  assert.equal("signRequest" in validated, false, "the server's proposal is not what gets signed");
});

test("order-action-challenge: the envelope is what callAuthorizedLifecycleTool expects and the challenge validates", () => {
  assert.equal(orderActionChallenge.authorizationRequired, true);
  assert.equal(orderActionChallenge.authorizationType, "OrderActionAuthorizationV1");
  const validated = validateOrderActionChallenge(orderActionChallenge.challenge, {
    orderHandle: HANDLE,
    action: "status",
    gatewayUrl: AUDIENCE,
    request: {},
    nowSeconds: FIXTURE_NOW,
    chainId: CHAIN_ID,
  });
  assert.equal(validated.orderId, "ord_00000000-0000-4000-8000-000000000001");
  assert.equal(validated.action, "status");
  assert.equal("signRequest" in validated, false, "the server's proposal is not what gets signed");
});

test("standard-rail-error: the MCP refusal and the HTTP envelopes carry their codes", () => {
  const denied = railErrors.mcpWalletAccessDenied;
  assert.equal(denied.isError, true);
  assert.equal(GatewayClient.json(denied)?.code, "WALLET_ACCESS_DENIED");
  assert.equal(GatewayClient.unreadable(denied), false);
  assert.equal(railErrors.walletAuthorizationInvalid.error.code, "WALLET_AUTHORIZATION_INVALID");
  assert.equal(railErrors.authorizationWindow.error.code, "AUTHORIZATION_WINDOW");
  assert.equal(railErrors.requestSchemaInvalid.error.code, "REQUEST_SCHEMA_INVALID");
});
